# Configuration for Educational QA Generation Pipeline

# Gemini API Configuration
gemini:
  # API key will be loaded from .env file
  model: "gemini-2.5-flash"
  temperature: 0.7
  max_output_tokens: 8192

# Pipeline Configuration
pipeline:
  input_folder: "input"
  output_folder: "output2"
  logs_folder: "logs"
  log_level: "INFO"
  log_file: "pipeline.log"

# Processing Configuration
processing:
  enable_grounding: true
  enable_google_search: true
  batch_size: 1  # Process one input file at a time
